config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'

  # resource :session, only: [:create, :destroy, :new]
  # resources :users, only: [:create, :new, :show, :index]

    namespace :api, defaults: { format: :json } do
        resource :session, only: [:create, :destroy, :show, :new]
        resources :users, only: [:show, :create, :index]
        resources :spots, only: [:index, :new, :create, :show]

        get 'spots/search', to: 'spots#search'
        resources :reviews, only: [:index, :create, :show, :update, :destroy]
        resources :taggings, only: [:index, :create, :show, :destroy]
        resources :tags, only: [:index, :create, :show]
    end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
    belongs_to :imageable, polymorphic: true
end

app/models/review.rb
class Review < ActiveRecord::Base
    validates :rating, inclusion: { in: [1, 2, 3, 4, 5],
        message: "Rating must be between 1-5" }

    validates :spot_id, :user_id, :rating, presence: true
    validates :user_id, uniqueness: { scope: :spot_id,
        message: "You can only review a spot once"}

    belongs_to :spot
    belongs_to :user
end

app/models/spot.rb
class Spot < ActiveRecord::Base
    validates :name, :lat, :lng, presence: true
    validates :approved, inclusion: { in: [true, false],
        message: "Can only be set to true or false" }

    has_many :reviews
    has_many :taggings
    has_many :tags,
        through: :taggings,
        source: :tag
    has_many :pictures, as: :imageable
    has_one :spot_address

    def self.in_bounds(bounds)
        self.where("lat < ?", bounds[:northEast][:lat])
        .where("lat > ?", bounds[:southWest][:lat])
        .where("lng > ?", bounds[:southWest][:lng])
        .where("lng < ?", bounds[:northEast][:lng])
    end

    def review_count
        reviews.count
    end

    def average_rating
        reviews.average(:rating)
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    validates :name, presence: true, uniqueness: true

    has_many :taggings, dependent: :destroy
    has_many :spots, through: :taggings, source: :spot

    # def self.queried_tags(str)
    #     partial = "%#{str.downcase}%"
    #     Tag.where("lower(name LIKE ?", partial)
    # end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
    validates :spot_id, :tag, presence: true
    validates :spot_id, uniqueness: { scope: :tag_id,
        message: "Location already has this tag"}

    belongs_to :spot
    belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_reader :password

    has_many :reviews
    has_one :picture, as: :imageable

    after_initialize :ensure_session_token

    validates :password_digest, presence: true
    validates(
        :password,
        length: { minimum: 6, allow_nil: true }
    )
    validates :session_token, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)

        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64(16)
        self.save!
        self.session_token
    end

    private

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64(16)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :current_user_id, :logged_in?

    private
    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by_session_token(session[:session_token])
    end

    def current_user_id
        current_user ? current_user.id : nil
    end

    def logged_in?
        !current_user.nil?
    end

    def login_user!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout_user!
        current_user.reset_session_token! unless current_user.nil?
        session[:session_token] = nil
    end

    def require_user!
        render json: ["Not logged in!"] if current_user.nil?
    end

    def require_no_user!
        render json: {error: "Already logged in"}, status: 400 if current_user
    end

    def require_login!
        render json: {error: "Not logged in"}, status: 401 if current_user.nil?
    end

    def require_logged_in!
        redirect_to new_session_url if current_user.nil?
    end

    def require_logged_out!
        redirect_to root_url if logged_in?
    end
end

app/controllers/sessions_controller.rb
# class SessionsController < ApplicationController
#     before_action :require_logged_in!, only: [:destroy]
#     before_action :require_logged_out!, only: [:new, :create]

#     def new
#         render :new
#     end

#     def create
#         user = User.find_by_credentials(
#             params[:user][:username],
#             params[:user][:password]
#         )

#         if user.nil?
#             flash.now[:errors] = ["Incorrect username and/or password"]
#             render :new
#         else
#             login_user!(user)
#             redirect_to :root
#         end
#     end

#     def destroy
#         logout_user!
#         redirect_to new_session_url
#     end
# end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def root
    end
end

app/controllers/users_controller.rb
# class UsersController < ApplicationController
#     before_action :require_logged_in!, only: [:index]
#     before_action :require_logged_out!, only: [:new, :create]

#     def index
#         @users = User.all
#         render :index
#     end

#     def new
#         @user = User.new
#         render :new
#     end

#     def create
#         @user = User.new(user_params)
#         if @user.save
#             login_user!(@user)
#             redirect_to :root
#         else
#             flash.now[:errors] = @user.errors.full_messages
#             render :new
#         end
#     end

#     private
#     def user_params
#         params.require(:user).permit(:password, :username)
#     end
# end

app/helpers/api/reviews_helper.rb
module Api::ReviewsHelper
end

app/helpers/api/spots_helper.rb
module Api::SpotsHelper
end

app/helpers/api/taggings_helper.rb
module Api::TaggingsHelper
end

app/helpers/api/tags_helper.rb
module Api::TagsHelper
end

app/helpers/api/user_helper.rb
module Api::UserHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flushr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
   <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300italic,300,700' rel='stylesheet' type='text/css'>
  <script src="https://widget.cloudinary.com/global/all.js" type="text/javascript"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDXYQNLz_yQujqBcURO2XRoN5ovdKR6r6k&libraries=places"
        type="text/javascript"></script>

  <meta name="description" content="Find public restrooms on the go wherever you are!" />

<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>
  <% if current_user %>
    <script>
      window.CURRENT_USER_ID = <%= current_user.id %>
    </script>
  <% end %>

    <!-- <%#= render partial: "shared/header" %> -->

  <%= yield %>

    <%= render partial: "shared/errors" %>

    <%= render partial: "shared/footer" %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">
        <ul>
            <li>Copyright &copy 2016 Flushr</li>
        </ul>

    <img src="/assets/skyline-light.png"
            height="230px" />
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="header-container">

    <div class="collapse navbar-collapse" id="collapse-menu">
        <ul class="nav navbar-nav pull-left">
            <div id="logo"><h3><a href="#">Flush</a></h3></div>
        </ul>

        <ul class="nav navbar-nav pull-right">
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                  <input type="text" class="form-control" placeholder="address, neighborhood, city, state or zip">
              </div>
              <button type="submit" class="btn btn-default">Search</button>
            </form>

            <li><a href="#">About Me</a></li>
            <li><a href="#">Write a Review</a></li>

            <% if current_user.nil? %>
                <li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign in", new_session_url %></button></li>
            <% else %>

                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <%= current_user.username %> <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="#">About Me</a></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Logout", session_url, method: :delete %></li>
                  </ul>
                </li>
             <% end %>

        </ul>
    </div>
  </div>
  </div>
  </nav>